name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'frontend/**'
      - '.github/workflows/docker-frontend.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/flutter-telegram-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/n
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest